---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: awx-ee-role
  namespace: awx
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-ee-rolebinding
  namespace: awx
subjects:
- kind: ServiceAccount
  name: awx-demo  # Or your custom SA
  namespace: awx
roleRef:
  kind: Role
  name: awx-ee-role
  apiGroup: rbac.authorization.k8s.io